drivers: hv: dxgkrnl: Remove argument in eventfd_signal()
Error Logs:
drivers/hv/dxgkrnl/dxgmodule.c: In function ‘signal_host_cpu_event’:
drivers/hv/dxgkrnl/dxgmodule.c:173:17: error: too many arguments to function ‘eventfd_signal’
  173 |                 eventfd_signal(event->cpu_event, 1);
      |                 ^~~~~~~~~~~~~~
In file included from drivers/hv/dxgkrnl/dxgmodule.c:15:
./include/linux/eventfd.h:87:20: note: declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |                    ^~~~~~~~~~~~~~

 * In 3652117f854819a148ff0fbe4492587d3520b5e5, eventfd_signal() has been simplified.
 * So We don't need to set "1" argument anymore.
 * This commit remove "1" argument in dxgmodule.c.

Signed-off-by: Yang Jeong Hun <onyxclover9931@gmail.com>