drivers: hv: dxgkrnl: Remove .fence_value_str and .timeline_value_str in dxgsyncfile
Error Logs:
drivers/hv/dxgkrnl/dxgsyncfile.c: At top level:
drivers/hv/dxgkrnl/dxgsyncfile.c:479:10: error: ‘const struct dma_fence_ops’ has no member named ‘fence_value_str’
  479 |         .fence_value_str = dxgdmafence_value_str,
      |          ^~~~~~~~~~~~~~~
drivers/hv/dxgkrnl/dxgsyncfile.c:479:28: error: initialization of ‘void (*)(struct dma_fence *, ktime_t)’ {aka ‘void (*)(struct dma_fence *, long long int)’} from incompatible pointer type ‘void (*)(struct dma_fence *, char *, int)’ [-Wincompatible-pointer-types]
  479 |         .fence_value_str = dxgdmafence_value_str,
      |                            ^~~~~~~~~~~~~~~~~~~~~
drivers/hv/dxgkrnl/dxgsyncfile.c:480:10: error: ‘const struct dma_fence_ops’ has no member named ‘timeline_value_str’
  480 |         .timeline_value_str = dxgdmafence_timeline_value_str,
      |          ^~~~~~~~~~~~~~~~~~
drivers/hv/dxgkrnl/dxgsyncfile.c:480:31: warning: excess elements in struct initializer
  480 |         .timeline_value_str = dxgdmafence_timeline_value_str,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 * In 2ce07fe, .fence_value_str and .timeline_value_str has been removed.
 * Remove them and also remove dxgdmafence_value_str and dxgdmafence_timeline_value_str.

Signed-off-by: Yang Jeong Hun <onyxclover9931@gmail.com>